// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpnAIKhAM_-27T97yABrOW5lDEO_V1hY',
    appId: '1:378886918937:web:bf07170269689b30ed2b88',
    messagingSenderId: '378886918937',
    projectId: 'utool-47dff',
    authDomain: 'utool-47dff.firebaseapp.com',
    databaseURL: 'https://utool-47dff-default-rtdb.firebaseio.com',
    storageBucket: 'utool-47dff.appspot.com',
    measurementId: 'G-3XVNXSNTZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybWRBWUEBrPcx7pbNWrAe3wX2H8H6Ptg',
    appId: '1:378886918937:android:980f95f68dd92619ed2b88',
    messagingSenderId: '378886918937',
    projectId: 'utool-47dff',
    databaseURL: 'https://utool-47dff-default-rtdb.firebaseio.com',
    storageBucket: 'utool-47dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKzYneMPyqb9cgIb46i0ywf9XTqP9xjE',
    appId: '1:378886918937:ios:2a2be2f97b1bcb72ed2b88',
    messagingSenderId: '378886918937',
    projectId: 'utool-47dff',
    databaseURL: 'https://utool-47dff-default-rtdb.firebaseio.com',
    storageBucket: 'utool-47dff.appspot.com',
    iosClientId: '378886918937-tpjndpif3erlesdpk3kmonl8fua8dmnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.utool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpKzYneMPyqb9cgIb46i0ywf9XTqP9xjE',
    appId: '1:378886918937:ios:2a2be2f97b1bcb72ed2b88',
    messagingSenderId: '378886918937',
    projectId: 'utool-47dff',
    databaseURL: 'https://utool-47dff-default-rtdb.firebaseio.com',
    storageBucket: 'utool-47dff.appspot.com',
    iosClientId: '378886918937-tpjndpif3erlesdpk3kmonl8fua8dmnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.utool',
  );
}
